package overflow.rebridge.domain.jobPosting;

public enum IndustryType {
    NONE,
    AGRICULTURE_FORESTRY_FISHERY,
    MINING,
    MANUFACTURING,
    ELECTRICITY_GAS_WATER,
    WASTE_ENVIRONMENT,
    CONSTRUCTION,
    WHOLESALE_RETAIL,
    TRANSPORTATION,
    ACCOMMODATION_FOOD,
    MEDIA_COMMUNICATION,
    FINANCE_INSURANCE,
    REAL_ESTATE,
    SCIENCE_TECH,
    BUSINESS_SUPPORT,
    PUBLIC_ADMINISTRATION,
    EDUCATION,
    HEALTH_SOCIAL_WORK,
    ARTS_SPORTS,
    ASSOCIATIONS_PERSONAL_SERVICES,
    HOUSEHOLD_SELF_PRODUCTION,
    INTERNATIONAL_ORGANIZATIONS
}
