spring:
  application:
    name: rebridge

  profiles:
    active: local  # 로컬에서 기본값. 운영에선 prod로 덮어쓰기

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

  config:
    import: classpath:application-secret.yml

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    max-http-form-post-size: 15MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

debug: true
